apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.redis.service.name }}
spec:
  selector:
    app: {{ .Values.redis.name }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.targetPort }}