---
# Source: counter-app/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-counter-secret
type: Opaque
data:
  REDIS_PASSWORD: "cGFzc3dvcmQxMjM="
---
# Source: counter-app/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-counter-config
data:
  REDIS_HOST: "redis-service"
---
# Source: counter-app/templates/redis-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: release-name-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
# Source: counter-app/templates/counter-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-counter-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: counter-app
---
# Source: counter-app/templates/redis-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-redis-service
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
---
# Source: counter-app/templates/app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-counter-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: counter-app
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
      - name: counter-app
        image: thomasalberto/counter-app:v2
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: release-name-counter-config
              key: REDIS_HOST
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: release-name-counter-secret
              key: REDIS_PASSWORD
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
---
# Source: counter-app/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: release-name-counter-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: release-name-counter-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
# Source: counter-app/templates/redis-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-redis
spec:
  serviceName: release-name-redis-service
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
  volumeClaimTemplates:
  - metadata:
      name: redis-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi
---
# Source: counter-app/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-counter-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: counter.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: release-name-counter-service
            port: 
              number: 80
